const moment = require('moment');

const fromBody = ({
    userId: user_id,
    clipId: clip_id,
    name,
    path,
    thumbnailPath: thumbnail_path,
    url,
    thumbnailURL: thumbnail_url,
    metadata,
    tags,
    status,
    type,
    uploadDate: upload_date,
    createdDate: created_date,
  }) => ({
    user_id,
    clip_id,
    name: name.trim(),
    path,
    thumbnail_path,
    url,
    thumbnail_url,
    metadata,
    tags,
    status,
    type,
    upload_date,
    created_date,
  })

const toBody = ({
    id,
    user_id: userId,
    clip_id: clipId,
    name,
    path,
    thumbnail_path: thumbnailPath,
    url,
    thumbnail_url: thumbnailURL,
    metadata,
    tags,
    status,
    type,
    upload_date: uploadDate,
    created_date: createdDate,
  }) => ({
    id,
    userId,
    clipId,
    name: name.trim(),
    path,
    thumbnailPath,
    url,
    thumbnailURL,
    metadata,
    tags,
    status,
    type,
    uploadDate,
    createdDate,
  })

  module.exports = {fromBody, toBody}