service: classifier-ocr

app: classifier
org: roosevelt

plugins:
  - serverless-attach-managed-policy

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  managedPolicyArns:
    - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
  memorySize: 3008
  timeout: 900
  region: us-east-2
  vpc:
    securityGroupIds:
      - sg-0c2e1def8b4098d16
    subnetIds:
      - subnet-0d98ce651f08cdb1e
      - subnet-0d2483828fd2c2264
      - subnet-08479fd01a2bdaa32
  environment:
    SRC_BUCKET: ${self:custom.source_bucket.${self:provider.stage}}
    DEST_BUCKET: ${self:custom.destination_bucket.${self:provider.stage}}
    CLIPPER_BUCKET: ${self:custom.clipper_bucket.${self:provider.stage}}
    PYTHONPATH: "/opt:/opt/python"

functions:

  get_events:
    runtime: python3.7
    handler: handler_ocr.get_events
    events:
      - s3:
          bucket: ${self:custom.source_bucket.${self:provider.stage}}
          existing: true
          event: s3:ObjectCreated:*
          maximumRetryAttempts: 0
          rules:
            - suffix: .ocr_json
    layers:
      - arn:aws:lambda:us-east-2:160492786134:layer:opencv4python37:1
      - arn:aws:lambda:us-east-2:160492786134:layer:tesseract-layer:1
      - arn:aws:lambda:us-east-2:160492786134:layer:pytesseract:1
      - arn:aws:lambda:us-east-2:160492786134:layer:fuzzywuzzy_p37:1

custom:
  stages:
    - dev
    - prod
  source_bucket:
    dev: "wizardlabs.gg-dev"
    prod: "wizardlabs.gg-prod"
  destination_bucket:
    dev: "wizardlabs.gg-dev"
    prod: "wizardlabs.gg-prod"
  clipper_bucket:
    dev: "wizardlabs-lamda-clips"
    prod: "wizardlabs-lamda-clips"